//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Askaiser.Marionette {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Askaiser.Marionette.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom property &apos;{0}&apos; is greater than the image height &apos;{1}&apos;..
        /// </summary>
        internal static string BitmapExtensions_Crop_Throw_BottomGreaterThanImageHeight {
            get {
                return ResourceManager.GetString("BitmapExtensions_Crop_Throw_BottomGreaterThanImageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left property &apos;{0}&apos; is greater than the image width &apos;{1}&apos;..
        /// </summary>
        internal static string BitmapExtensions_Crop_Throw_LeftGreaterThanImageWidth {
            get {
                return ResourceManager.GetString("BitmapExtensions_Crop_Throw_LeftGreaterThanImageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New height cannot be zero..
        /// </summary>
        internal static string BitmapExtensions_Crop_Throw_NewHeightZero {
            get {
                return ResourceManager.GetString("BitmapExtensions_Crop_Throw_NewHeightZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New width cannot be zero..
        /// </summary>
        internal static string BitmapExtensions_Crop_Throw_NewWidthZero {
            get {
                return ResourceManager.GetString("BitmapExtensions_Crop_Throw_NewWidthZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right property &apos;{0}&apos; is greater than the image width &apos;{1}&apos;..
        /// </summary>
        internal static string BitmapExtensions_Crop_Throw_RightGreaterThanImageWidth {
            get {
                return ResourceManager.GetString("BitmapExtensions_Crop_Throw_RightGreaterThanImageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top property &apos;{0}&apos; is greater than the image height &apos;{1}&apos;..
        /// </summary>
        internal static string BitmapExtensions_Crop_Throw_TopGreaterThanImageHeight {
            get {
                return ResourceManager.GetString("BitmapExtensions_Crop_Throw_TopGreaterThanImageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default &apos;sleepAfter&apos; duration cannot be negative..
        /// </summary>
        internal static string DriverOptions_Throw_NegativeDefaultKeyboardSleepAfterDuration {
            get {
                return ResourceManager.GetString("DriverOptions_Throw_NegativeDefaultKeyboardSleepAfterDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default &apos;waitFor&apos; duration cannot be negative..
        /// </summary>
        internal static string DriverOptions_Throw_NegativeDefaultWaitForDuration {
            get {
                return ResourceManager.GetString("DriverOptions_Throw_NegativeDefaultWaitForDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot cache duration cannot be negative..
        /// </summary>
        internal static string DriverOptions_Throw_NegativeScreenshotCacheDuration {
            get {
                return ResourceManager.GetString("DriverOptions_Throw_NegativeScreenshotCacheDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element &apos;{0}&apos; was not found..
        /// </summary>
        internal static string Element_Throw_ElementNotFound {
            get {
                return ResourceManager.GetString("Element_Throw_ElementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be null or empty..
        /// </summary>
        internal static string Element_Throw_InvalidName {
            get {
                return ResourceManager.GetString("Element_Throw_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An element with the name &apos;{0}&apos; already exists..
        /// </summary>
        internal static string ElementCollectionExtensions_Throw_ElementAlreadyExists {
            get {
                return ResourceManager.GetString("ElementCollectionExtensions_Throw_ElementAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An element cannot have a null or empty name..
        /// </summary>
        internal static string ElementCollectionExtensions_Throw_InvalidElementName {
            get {
                return ResourceManager.GetString("ElementCollectionExtensions_Throw_InvalidElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The JSON document cannot null elements..
        /// </summary>
        internal static string ElementCollectionExtensions_Throw_NullJsonElement {
            get {
                return ResourceManager.GetString("ElementCollectionExtensions_Throw_NullJsonElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element of type &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string ElementCollectionExtensions_Throw_UnsupportedElementType {
            get {
                return ResourceManager.GetString("ElementCollectionExtensions_Throw_UnsupportedElementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element &apos;{0}&apos; was not found within the allotted time: {1}..
        /// </summary>
        internal static string ElementNotFoundException_Message_WithDuration {
            get {
                return ResourceManager.GetString("ElementNotFoundException_Message_WithDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element &apos;{0}&apos; was not found..
        /// </summary>
        internal static string ElementNotFoundException_Message_WithoutDuration {
            get {
                return ResourceManager.GetString("ElementNotFoundException_Message_WithoutDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:yyyy-MM-dd-HH-mm-ss-ffff}_{1}.png.
        /// </summary>
        internal static string FailureScreenshotFileNameFormat {
            get {
                return ResourceManager.GetString("FailureScreenshotFileNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content must be a non-empty array of bytes..
        /// </summary>
        internal static string ImageElement_Throw_EmptyContent {
            get {
                return ResourceManager.GetString("ImageElement_Throw_EmptyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold must be a floating number between 0 and 1..
        /// </summary>
        internal static string ImageElement_Throw_ThresholdOutOfRange {
            get {
                return ResourceManager.GetString("ImageElement_Throw_ThresholdOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text parameter is too long. It must be less than {0} characters..
        /// </summary>
        internal static string KeyboardSimulator_Throw_TextTooLong {
            get {
                return ResourceManager.GetString("KeyboardSimulator_Throw_TextTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements cannot be empty..
        /// </summary>
        internal static string MarionetteDriver_Throw_ElementsEmpty {
            get {
                return ResourceManager.GetString("MarionetteDriver_Throw_ElementsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key codes cannot be empty..
        /// </summary>
        internal static string MarionetteDriver_Throw_EmptyKeyCodes {
            get {
                return ResourceManager.GetString("MarionetteDriver_Throw_EmptyKeyCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll ticks must be greater than zero..
        /// </summary>
        internal static string MarionetteDriver_Throw_ScrollTicksNotGreaterThanZero {
            get {
                return ResourceManager.GetString("MarionetteDriver_Throw_ScrollTicksNotGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor #{0} {1} {2}x{3}.
        /// </summary>
        internal static string MonitorDescription_ToString {
            get {
                return ResourceManager.GetString("MonitorDescription_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested monitor index &apos;{0}&apos; not found..
        /// </summary>
        internal static string MonitorService_Throw_MonitorNotFound {
            get {
                return ResourceManager.GetString("MonitorService_Throw_MonitorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element &apos;{0}&apos; was found at multiple locations: {1}..
        /// </summary>
        internal static string MultipleElementFoundException_Message {
            get {
                return ResourceManager.GetString("MultipleElementFoundException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0},{1}).
        /// </summary>
        internal static string Point_ToString {
            get {
                return ResourceManager.GetString("Point_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left property &apos;{0}&apos; cannot be greater than the Right property &apos;{1}&apos;..
        /// </summary>
        internal static string Rectangle_Throw_LeftGreaterThanRight {
            get {
                return ResourceManager.GetString("Rectangle_Throw_LeftGreaterThanRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top property &apos;{0}&apos; cannot be greater than the Bottom property &apos;{1}&apos;..
        /// </summary>
        internal static string Rectangle_Throw_TopGreaterThanBottom {
            get {
                return ResourceManager.GetString("Rectangle_Throw_TopGreaterThanBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0},{1},{2},{3}).
        /// </summary>
        internal static string Rectangle_ToString {
            get {
                return ResourceManager.GetString("Rectangle_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results for &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string SearchResult_ToString {
            get {
                return ResourceManager.GetString("SearchResult_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results cannot be empty..
        /// </summary>
        internal static string SearchResultCollection_Throw_ResultsEmpty {
            get {
                return ResourceManager.GetString("SearchResultCollection_Throw_ResultsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content cannot be null or empty..
        /// </summary>
        internal static string TextElement_Throw_EmptyContent {
            get {
                return ResourceManager.GetString("TextElement_Throw_EmptyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for duration cannot be negative..
        /// </summary>
        internal static string Throw_NegativeWaitFor {
            get {
                return ResourceManager.GetString("Throw_NegativeWaitFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input array was empty..
        /// </summary>
        internal static string WindowsInputMessageDispatcher_Throw_EmptyInputs {
            get {
                return ResourceManager.GetString("WindowsInputMessageDispatcher_Throw_EmptyInputs", resourceCulture);
            }
        }
    }
}
